// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPtBgtt6E83eT9bcB5HJIIjxUC6rOgzk8',
    appId: '1:573069522091:web:da800ab4e07070268ab3ee',
    messagingSenderId: '573069522091',
    projectId: 'e-campus-de3be',
    authDomain: 'e-campus-de3be.firebaseapp.com',
    storageBucket: 'e-campus-de3be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qK7hRXWHrKJB9BSHVRG3Ry7oSmz424Y',
    appId: '1:573069522091:android:58a6d314df5153d88ab3ee',
    messagingSenderId: '573069522091',
    projectId: 'e-campus-de3be',
    storageBucket: 'e-campus-de3be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAflo3sCI6in15o-1x478X2t4C_3mwCsrc',
    appId: '1:573069522091:ios:8a1edb453fd596aa8ab3ee',
    messagingSenderId: '573069522091',
    projectId: 'e-campus-de3be',
    storageBucket: 'e-campus-de3be.firebasestorage.app',
    iosBundleId: 'com.example.eCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAflo3sCI6in15o-1x478X2t4C_3mwCsrc',
    appId: '1:573069522091:ios:8a1edb453fd596aa8ab3ee',
    messagingSenderId: '573069522091',
    projectId: 'e-campus-de3be',
    storageBucket: 'e-campus-de3be.firebasestorage.app',
    iosBundleId: 'com.example.eCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPtBgtt6E83eT9bcB5HJIIjxUC6rOgzk8',
    appId: '1:573069522091:web:4fe966d01491b8678ab3ee',
    messagingSenderId: '573069522091',
    projectId: 'e-campus-de3be',
    authDomain: 'e-campus-de3be.firebaseapp.com',
    storageBucket: 'e-campus-de3be.firebasestorage.app',
  );
}
